image: openjdk:8-jdk

stages:
  - build
  - publish

build:
  stage: build
  script:
    - ./gradlew build

publishBintray:
  stage: publish
  only:
    - tags
  script:
    - ./gradlew -d bintrayUpload