image: openjdk:8-jdk

stages:
  - build
  - publish

build:
  stage: build
  script:
    - ./gradlew build

testenv:
    stage: publish
    script:
        - env

publishBintray:
  stage: publish
  only:
    - tags
  script:
    - ./gradlew bintrayUpload